//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace RestroomLocator.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RestroomLocatorEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RestroomLocatorEntities object using the connection string found in the 'RestroomLocatorEntities' section of the application configuration file.
        /// </summary>
        public RestroomLocatorEntities() : base("name=RestroomLocatorEntities", "RestroomLocatorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RestroomLocatorEntities object.
        /// </summary>
        public RestroomLocatorEntities(string connectionString) : base(connectionString, "RestroomLocatorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RestroomLocatorEntities object.
        /// </summary>
        public RestroomLocatorEntities(EntityConnection connection) : base(connection, "RestroomLocatorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RestRoom> RestRooms
        {
            get
            {
                if ((_RestRooms == null))
                {
                    _RestRooms = base.CreateObjectSet<RestRoom>("RestRooms");
                }
                return _RestRooms;
            }
        }
        private ObjectSet<RestRoom> _RestRooms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UsersRating> UsersRatings
        {
            get
            {
                if ((_UsersRatings == null))
                {
                    _UsersRatings = base.CreateObjectSet<UsersRating>("UsersRatings");
                }
                return _UsersRatings;
            }
        }
        private ObjectSet<UsersRating> _UsersRatings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RestRooms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRestRooms(RestRoom restRoom)
        {
            base.AddObject("RestRooms", restRoom);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UsersRatings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsersRatings(UsersRating usersRating)
        {
            base.AddObject("UsersRatings", usersRating);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestroomLocatorModel", Name="RestRoom")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RestRoom : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RestRoom object.
        /// </summary>
        /// <param name="restRoomId">Initial value of the RestRoomId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static RestRoom CreateRestRoom(global::System.Int64 restRoomId, global::System.String name, global::System.String address)
        {
            RestRoom restRoom = new RestRoom();
            restRoom.RestRoomId = restRoomId;
            restRoom.Name = name;
            restRoom.Address = address;
            return restRoom;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RestRoomId
        {
            get
            {
                return _RestRoomId;
            }
            set
            {
                if (_RestRoomId != value)
                {
                    OnRestRoomIdChanging(value);
                    ReportPropertyChanging("RestRoomId");
                    _RestRoomId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RestRoomId");
                    OnRestRoomIdChanged();
                }
            }
        }
        private global::System.Int64 _RestRoomId;
        partial void OnRestRoomIdChanging(global::System.Int64 value);
        partial void OnRestRoomIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                if (_Name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                if (_Address != value)
                {
                    OnAddressChanging(value);
                    ReportPropertyChanging("Address");
                    _Address = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Address");
                    OnAddressChanged();
                }
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lattitude
        {
            get
            {
                return _Lattitude;
            }
            set
            {
                OnLattitudeChanging(value);
                ReportPropertyChanging("Lattitude");
                _Lattitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lattitude");
                OnLattitudeChanged();
            }
        }
        private global::System.String _Lattitude;
        partial void OnLattitudeChanging(global::System.String value);
        partial void OnLattitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.String _Longitude;
        partial void OnLongitudeChanging(global::System.String value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cost
        {
            get
            {
                return _Cost;
            }
            set
            {
                OnCostChanging(value);
                ReportPropertyChanging("Cost");
                _Cost = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Cost");
                OnCostChanged();
            }
        }
        private global::System.String _Cost;
        partial void OnCostChanging(global::System.String value);
        partial void OnCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WhoCanAccess
        {
            get
            {
                return _WhoCanAccess;
            }
            set
            {
                OnWhoCanAccessChanging(value);
                ReportPropertyChanging("WhoCanAccess");
                _WhoCanAccess = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WhoCanAccess");
                OnWhoCanAccessChanged();
            }
        }
        private global::System.String _WhoCanAccess;
        partial void OnWhoCanAccessChanging(global::System.String value);
        partial void OnWhoCanAccessChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Timings
        {
            get
            {
                return _Timings;
            }
            set
            {
                OnTimingsChanging(value);
                ReportPropertyChanging("Timings");
                _Timings = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Timings");
                OnTimingsChanged();
            }
        }
        private global::System.String _Timings;
        partial void OnTimingsChanging(global::System.String value);
        partial void OnTimingsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsDeleted
        {
            get
            {
                return _IsDeleted;
            }
            set
            {
                OnIsDeletedChanging(value);
                ReportPropertyChanging("IsDeleted");
                _IsDeleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDeleted");
                OnIsDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsDeleted;
        partial void OnIsDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastChgDate
        {
            get
            {
                return _LastChgDate;
            }
            set
            {
                OnLastChgDateChanging(value);
                ReportPropertyChanging("LastChgDate");
                _LastChgDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastChgDate");
                OnLastChgDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastChgDate;
        partial void OnLastChgDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastChgDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastChgUser
        {
            get
            {
                return _LastChgUser;
            }
            set
            {
                OnLastChgUserChanging(value);
                ReportPropertyChanging("LastChgUser");
                _LastChgUser = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastChgUser");
                OnLastChgUserChanged();
            }
        }
        private global::System.String _LastChgUser;
        partial void OnLastChgUserChanging(global::System.String value);
        partial void OnLastChgUserChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RestroomLocatorModel", Name="UsersRating")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UsersRating : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UsersRating object.
        /// </summary>
        /// <param name="usersRatingId">Initial value of the UsersRatingId property.</param>
        public static UsersRating CreateUsersRating(global::System.Int64 usersRatingId)
        {
            UsersRating usersRating = new UsersRating();
            usersRating.UsersRatingId = usersRatingId;
            return usersRating;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 UsersRatingId
        {
            get
            {
                return _UsersRatingId;
            }
            set
            {
                if (_UsersRatingId != value)
                {
                    OnUsersRatingIdChanging(value);
                    ReportPropertyChanging("UsersRatingId");
                    _UsersRatingId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UsersRatingId");
                    OnUsersRatingIdChanged();
                }
            }
        }
        private global::System.Int64 _UsersRatingId;
        partial void OnUsersRatingIdChanging(global::System.Int64 value);
        partial void OnUsersRatingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> RestRoomId
        {
            get
            {
                return _RestRoomId;
            }
            set
            {
                OnRestRoomIdChanging(value);
                ReportPropertyChanging("RestRoomId");
                _RestRoomId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RestRoomId");
                OnRestRoomIdChanged();
            }
        }
        private Nullable<global::System.Int64> _RestRoomId;
        partial void OnRestRoomIdChanging(Nullable<global::System.Int64> value);
        partial void OnRestRoomIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> CleannessRating
        {
            get
            {
                return _CleannessRating;
            }
            set
            {
                OnCleannessRatingChanging(value);
                ReportPropertyChanging("CleannessRating");
                _CleannessRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CleannessRating");
                OnCleannessRatingChanged();
            }
        }
        private Nullable<global::System.Int16> _CleannessRating;
        partial void OnCleannessRatingChanging(Nullable<global::System.Int16> value);
        partial void OnCleannessRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> PrivacyRating
        {
            get
            {
                return _PrivacyRating;
            }
            set
            {
                OnPrivacyRatingChanging(value);
                ReportPropertyChanging("PrivacyRating");
                _PrivacyRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrivacyRating");
                OnPrivacyRatingChanged();
            }
        }
        private Nullable<global::System.Int16> _PrivacyRating;
        partial void OnPrivacyRatingChanging(Nullable<global::System.Int16> value);
        partial void OnPrivacyRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserComments
        {
            get
            {
                return _UserComments;
            }
            set
            {
                OnUserCommentsChanging(value);
                ReportPropertyChanging("UserComments");
                _UserComments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserComments");
                OnUserCommentsChanged();
            }
        }
        private global::System.String _UserComments;
        partial void OnUserCommentsChanging(global::System.String value);
        partial void OnUserCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastChgDate
        {
            get
            {
                return _LastChgDate;
            }
            set
            {
                OnLastChgDateChanging(value);
                ReportPropertyChanging("LastChgDate");
                _LastChgDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastChgDate");
                OnLastChgDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastChgDate;
        partial void OnLastChgDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastChgDateChanged();

        #endregion

    
    }

    #endregion

    
}
